version: 2

sources:
  - name: staging
    database: terraform-de-411309
     # For postgres:
      #database: production
    schema: taxi_rides_all

      # loaded_at_field: record_loaded_at
    tables:
      - name: green_taxi
      - name: yellow_taxi
         # freshness:
           # error_after: {count: 6, period: hour}
